# tasks file
---
- name: configure
  when: netplan_conf_purge | bool
  tags:
    - netplan-configure-purge
  block:
    - name: configure | find existing
      ansible.builtin.find:
        paths: "{{ netplan_conf_path }}"
        patterns: '*.yaml,*.yml'
      register: _netplan_existing_files

    - name: configure | remove existing
      ansible.builtin.file:
        path: "{{ item['path'] }}"
        state: absent
      with_items: "{{ _netplan_existing_files['files'] }}"
      when:
        - item['path'] != netplan_conf_path + '/' + netplan_conf_file

- name: configure | update
  ansible.builtin.template:
    src: etc/netplan/config.yaml.j2
    dest: "{{ netplan_conf_path }}/{{ netplan_conf_file }}"
    mode: 0644
    backup: yes
  when: netplan_conf | length
  notify:
    - generate netplan config
    - apply netplan config
  tags:
    - netplan-configure-update
