# tasks file
---
- name: install
  ansible.builtin.import_tasks: install.yml
  when: netplan_install_packages
  tags:
    - configuration
    - netplan
    - netplan-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - netplan
    - netplan-configure
